---

- name: Create Prometheus ElasticSearch Exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_exporter_user }}"
    group: "{{ elasticsearch_exporter_group }}"
    mode: 0750
  with_items:
    - "{{ elasticsearch_exporter_install_path }}"
    - "{{ elasticsearch_exporter_install_path }}/bin"
    - "{{ elasticsearch_exporter_log_path }}"

- name: stat downloaded exporter tar
  stat:
    path: "{{ elasticsearch_exporter_download_dest }}/{{ elasticsearch_exporter_download_url.split('/')[-1] }}"
  register: download_tar

- name: Download Prometheus ElasticSearch Exporter tarball
  get_url:
    url: "{{ elasticsearch_exporter_download_url }}"
    dest: "{{ elasticsearch_exporter_download_dest }}"
    checksum: "{{ elasticsearch_exporter_checksum }}"
  when: download_tar.stat.exists == False

- name: Untar Prometheus ElasticSearch Exporter tarball
  unarchive:
    src: "{{ elasticsearch_exporter_download_dest }}/{{ elasticsearch_exporter_download_url.split('/')[-1] }}"
    dest: "{{ elasticsearch_exporter_install_path }}"
    owner: "{{ elasticsearch_exporter_user }}"
    group: "{{ elasticsearch_exporter_user }}"
    remote_src: True
  when: download_tar.stat.exists == False

- name: Ensure Prometheus ElasticSearch Exporter directory does not exist
  file:
    path: "{{ elasticsearch_exporter_install_path }}/prometheus_elasticsearch_exporter/"
    state: absent
  when: download_tar.stat.exists == False

- name: Move Prometheus ElasticSearch Exporter directory to destination
  become: yes
  become_user: "{{ elasticsearch_exporter_user }}"
  command: "mv {{ elasticsearch_exporter_install_path }}/{{ elasticsearch_exporter_download_url.split('/')[-1].rsplit('.',2)[0] }} {{ elasticsearch_exporter_install_path }}/prometheus_elasticsearch_exporter"
  when: download_tar.stat.exists == False

- name: Add elasticsearch_exporter default file
  template:
    src: "elasticsearch_exporter.default.j2"
    dest: "/etc/default/elasticsearch_exporter"
  notify: "restart exporter"

- name: Add systemd service
  template:
    dest: /etc/systemd/system/elasticsearch-exporter.service
    mode: 0775
    src: elasticsearch_exporter.service.j2
  notify: "restart exporter"
