---

- name: Create dedicated Prometheus ElasticSearch Exporter user
  include: user_creation.yml
  tags:
    - build

- name: Install Prometheus ElasticSearch Exporter
  include: build.yml
  tags:
    - build

- name: Configure Prometheus ElasticSearch Exporter
  include: configure.yml
  tags:
    - configure
